<?php
// $Id$

/**
 * @file
 * Exposes a testpage for HTML5 FAPI
 */

/**
 * Implements hook_element_info_alter().
 */
function html5fapi_element_info_alter(&$type) {
  $types = array(
    'textfield',
    'textarea',
    'radio',
    'radios',
    'checkbox',
    'checkboxes',
    'password',
    'password_confirm',
    'select'
  );
  foreach($types as $name) {
    if (isset($type[$name])) {
      $type[$name]['#process'][] = 'html5fapi_form_process';
    }
  }
}

/**
 * Adds support for HTML5 attributes
 */
function html5fapi_form_process($element) {
  $attributes = array(
    'maxlength',
    'pattern',
    'placeholder',
    //'min',
    //'max',
    //'autocomplete',
    //'list',
    //'accept',
  );
  // Exceptions for attributes that don't really take a value
  $specialones = array(
    'required',
    'autofocus',
    //'multiple',
    //'readonly'
  );
  foreach ($attributes as $attribute) {
    if (isset($element['#' . $attribute])) {
      $element['#attributes'][$attribute] = $element['#' . $attribute];
    }
  }
  foreach ($specialones as $attribute) {
    if (isset($element['#' . $attribute]) && $element['#' . $attribute]) {
      $element['#attributes'][$attribute] = $attribute;
    }
  }
  return $element;
}
